/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AgentRegistry__factory } from "./AgentRegistry__factory";
export { IAgentRegistry__factory } from "./IAgentRegistry__factory";
